.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_SERVER_BACKUP" "8" "June 2021" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_server_backup\fR \- Creates a backup of all databases in the given Stardog instance
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR [ \-\-krb5 ] [ \-\-krb5\-disable\-rdns ] [ \-\-server \fIserver url\fR ] \fBserver\fR \fBbackup\fR [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ \-\-run\-as \fIusername\fR ] [ {\-u | \-\-username} \fIusername\fR ] [ {\-v | \-\-verbose} ] [\-\-] [ \fIBackup location\fR ]
.
.SH "OPTIONS"
.
.TP
\fB\-\-krb5\fR
Use the Kerberos environment\.
.
.TP
\fB\-\-krb5\-disable\-rdns\fR
Disable reverse DNS lookup for Kerberos clients\.
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-run\-as\fR \fIusername\fR
User to impersonate when running the command
.
.TP
\fB\-\-server\fR \fIserver url\fR
URL of Stardog Server\. If this option isn\'t specified, it will be read from JVM argument \'stardog\.default\.cli\.server\'\. If the JVM arg isn\'t set, the default value \'http://localhost:5820\' is used\. If server URL has no explicit port value, the default port value \'5820\' is used\. Example: \'stardog\-admin \-\-server http://12\.34\.56\.78:5820 server stop\'
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Flag that can cause more detailed information to be printed such as errors and status\. Exact output depends upon the command and options used\.
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIBackup location\fR
Provide a specific location to save the backup on the server side; overrides the default location\.
.
.SH "DISCUSSION"
Creates a backup of all databases in the given Stardog instance\. By default, backups are stored in the \'\.backup\' directory in your Stardog home, but you can use the \'backup\.dir\' property in your \'stardog\.configuration\' file to specify a different location for backups or you can override any default\.
.
.SH "EXAMPLES"
.
.TP
Create a backup of all databases in the default backup directory:
$ stardog\-admin server backup
.
.TP
Create a backup of all databases and save it in the given location
$stardog\-admin server backup /path/to/backup/dir/on/server

