.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_ZK_INFO" "8" "June 2021" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_zk_info\fR \- Prints the data Stardog stores in a ZooKeeper cluster\.
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR \fBzk\fR \fBinfo\fR [ \-\-home \fIhome\fR ] [ {\-v | \-\-verbose} ] [ \-\-zkauth \fIauth\fR ] [\-\-] [ \fIzkAddress\fR ]
.
.SH "OPTIONS"
.
.TP
\fB\-\-home\fR \fIhome\fR
Stardog home directory location\. This is where the stardog\.properties file is located at\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Flag that can cause more detailed information to be printed such as errors and status\. Exact output depends upon the command and options used\.
.
.TP
\fB\-\-zkauth\fR \fIauth\fR
Zookeeper authentication string\. If this value is not provided the value for the configuration option \'pack\.zookeeper\.auth\' from stardog\.properties is used\. If that value is not set either then the default value \'admin:admin\' will be used\.
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIzkAddress\fR
Zookeeper connection string\. If this value is not provided the value for the configuration option \'pack\.zookeeper\.auth\' from stardog\.properties is used\.
.
.SH "DISCUSSION"
This command connects to a Zookeeper cluster and prints the data stored by Stardog\.
.
.SH "EXAMPLES"
.
.TP
Connects to a Zookeeper at the given address and prints the data:
$ stardog\-admin zk info 127\.0\.0\.1:2180
.
.TP
Connects to a Zookeeper at the given address with the given authentication string and prints the data:
$ stardog\-admin zk info \-\-zkauth my_secret_key 127\.0\.0\.1:2180
.
.TP
Read the Zookeeper address and the authentication string from stardog\.properties in the specified home directory:
$ stardog\-admin zk info \-\-home stardog_home_path
.
.TP
Read the Zookeeper address and the authentication string from stardog\.properties in $STARDOG_HOME:
$ stardog\-admin zk info

