.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_CACHE_TARGET" "8" "June 2021" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_cache_target\fR \- List, add or remove cache targets\.
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR [ \-\-krb5 ] [ \-\-krb5\-disable\-rdns ] [ \-\-server \fIserver url\fR ] \fBcache\fR \fBtarget\fR [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ \-\-run\-as \fIusername\fR ] [ {\-u | \-\-username} \fIusername\fR ] [ \-\-use\-existing\-database ] [ {\-v | \-\-verbose} ] [\-\-] [ \fIhostnameAndPort\fR \fIusername\fR \fIpassword\fR\.\.\. ]
.
.SH "OPTIONS"
.
.TP
\fB\-\-krb5\fR
Use the Kerberos environment\.
.
.TP
\fB\-\-krb5\-disable\-rdns\fR
Disable reverse DNS lookup for Kerberos clients\.
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-run\-as\fR \fIusername\fR
User to impersonate when running the command
.
.TP
\fB\-\-server\fR \fIserver url\fR
URL of Stardog Server\. If this option isn\'t specified, it will be read from JVM argument \'stardog\.default\.cli\.server\'\. If the JVM arg isn\'t set, the default value \'http://localhost:5820\' is used\. If server URL has no explicit port value, the default port value \'5820\' is used\. Example: \'stardog\-admin \-\-server http://12\.34\.56\.78:5820 server stop\'
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-\-use\-existing\-database\fR
Check for an existing cache database to use before creating a new one\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Flag that can cause more detailed information to be printed such as errors and status\. Exact output depends upon the command and options used\.
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIhostnameAndPort\fR \fIusername\fR \fIpassword\fR
The hostname (optionally including port, default=5820), username and password of the cache target\.
.
.SH "EXAMPLES"
.
.TP
Lists the existing cache targets
$ stardog\-admin cache target list
.
.TP
Adds a new cache target
$ stardog\-admin cache target add node1 mynode\.mydomain:5820 user pass
.
.TP
Remove a cache target and destroy its contents
$ stardog\-admin cache target remove node1
.
.TP
Orphan a cache target but do not destroy the contents
$ stardog\-admin cache target orphan node1
.
.TP
Add a cache target that uses an existing cache database
$ stardog\-admin cache target add node1 mynode\.mydomain:5820 user pass \-\-use\-existing\-database

