.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_ROCKS_LDB" "8" "June 2021" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_rocks_ldb\fR \- Low\-Level Administration and Data Access Tool
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR \fBrocks\fR \fBldb\fR [ \-\-home \fIhome\fR ] [ \-s \fIencryption passphrase\fR ] [ {\-v | \-\-verbose} ] [\-\-] [ \fImArgs\fR\.\.\. ]
.
.SH "OPTIONS"
.
.TP
\fB\-\-home\fR \fIhome\fR
Stardog home directory location\.
.
.TP
\fB\-s\fR \fIencryption passphrase\fR
passphrase to access encrypted databases
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Flag that can cause more detailed information to be printed such as errors and status\. Exact output depends upon the command and options used\.
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fImArgs\fR
Remaining LDB options
.
.SH "DISCUSSION"
The ldb command line tool offers multiple data access and database admin commands see https://github\.com/facebook/rocksdb/wiki/Administration\-and\-Data\-Access\-Tool
.
.SH "EXAMPLES"
.
.TP
Print detailed help
$ stardog\-admin rocks ldb \-\-help
.
.TP
List the column families
$ stardog\-admin rocks ldb \-\-home /stardog_home/ list_column_families
.
.TP
Dump the manifest file contents
$ stardog\-admin rocks ldb \-\-home /stardog_home/ manifest_dump
.
.TP
Compact the database
$ stardog\-admin rocks ldb \-\-home /stardog_home/ compact
.
.TP
Get a key
$ stardog\-admin rocks ldb \-\-home /stardog_home/ get <key>

